### ISSUE TITLE
Padding error 

### ISSUE THREAD

**Issue by wadmin666** [XML-Security/signxml#158]
When i'm using code from example i'm getting this error : 
```

Traceback (most recent call last):
  File "sign.py", line 9, in <module>
    signed_root = XMLSigner(method=signxml.methods.enveloped).sign(root, key=key, cert=cert)
  File "/home/rotten91/.local/lib/python3.8/site-packages/signxml/__init__.py", line 394, in sign
    signature = key.sign(signed_info_c14n, padding=PKCS1v15(), algorithm=hash_alg)
TypeError: sign() got an unexpected keyword argument 'padding'

```

**Comment by kislyuk** [comment]
The key parameter that you are passign to the sign() method is not of a compatible type.

 If you need help, please provide a complete reproduction of the issue you are facing, including complete example code and the difference between what you are expecting and what you see.

I am going to close this issue for now because it does not provide the level of detail necessary to provide further help. Feel free to post more details to get the issue reopened, or open a new issue.
