### ISSUE TITLE
Compatibility with PyInstaller

### ISSUE THREAD

**Issue by ilvalle** [XML-Security/signxml#16]
When creating a package with pyinstaller I've an issue because xmldsig1-schema.xsd is not included. The application is executed in a temporary directory, and the file path should be for example `C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\_MEI46203\\signxml\\schemas\\xmldsi
g1-schema.xsd`

A potential workaround would be to specify at run-time the directory path containing xmldsig1-schema.xsd and the other schemas. es:

```
signxml.xmldsig(rootXML, schemas_dir=...)
```

Is it feasible?

**Comment by kislyuk** [comment]
Is there a way to make pyinstaller obey the contents of https://github.com/kislyuk/signxml/blob/master/MANIFEST.in?

**Comment by ilvalle** [comment]
don't know, I'm not a master of pyinstaller, maybe with hooks? perhaps @matysek can help

**Comment by matysek** [comment]
Regarding pyinstaller, this looks like a usecase for data files: https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Collect-Data-Files

**Comment by kislyuk** [comment]
Not going to do anything about this. If the installation software that you use follows the setuptools protocol, then the schemas are going to be included.

**Comment by bvanelli** [comment]
The problem is still happening on the latest version. I tried a bunch of different things like including the library data with multiple methods but nothing seemed to work.

I don't *really* know where the problem is, but my best guess is that the loader cannot deal with the xml includes when being called from the pyinstaller frozen environment.

If anyone is interested, here is my (very very ugly) workaround, I instead imported and parsed as a python file (that is for sure included in pyinstaller). You can see the changes here (only core was included, so some functionality might be lost):

https://github.com/bvanelli/signxml/commit/82052d4647548643d386940d3e2dfea7ba4a89d7

The result successfully runs on a pyinstaller environment (tested on python 3.8, pyinstaller 3.6).

**Comment by kislyuk** [comment]
From the pyinstaller documentation, it looks like you are looking for the `--add-data` option.

**Comment by bvanelli** [comment]
@kislyuk I tried this already by including a custom hook for the library.

```python
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files("signxml")
```

This collects all the files correctly but the result still fails to run. The same happens with --add-data (under the hood is the same thing):

```bash
pyinstaller -F --add-data "signxml/schemas/*:signxml/schemas"  script.py
```

### How to reproduce

On the repo top level create a script:

```
example_key = """
KEY HERE
""".encode()

example_pem = """
CERT HERE
""".encode()

from lxml import etree
from signxml import XMLSigner, XMLVerifier

data_to_sign = "<Test/>"
root = etree.fromstring(data_to_sign)
signed_root = XMLSigner().sign(root, key=example_key, cert=example_pem)
verified_data = XMLVerifier().verify(signed_root, x509_cert=example_pem).signed_xml
print("Finished successfully)
```

Run pyinstaller:

```bash
pyinstaller -F --add-data "signxml/schemas/*:signxml/schemas"  script.py
```

There are no errrors on the bundling. If you check the .spec file, the files are included:

```python
a = Analysis(['script.py'],
             ...,
             datas=[('signxml/schemas/*', 'signxml/schemas')],
             ...)
```

But unfortunatelly it fails to run:

```bash
> ./dist/script 
Traceback (most recent call last):
  File "script.py", line 57, in <module>
    verified_data = XMLVerifier().verify(signed_root, x509_cert=example_pem).signed_xml
  File "signxml/__init__.py", line 806, in verify
    self.schema().assertValid(signature)
  File "signxml/util/__init__.py", line 140, in schema
    cls._schema = etree.XMLSchema(etree.parse(schema_path))
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file '/tmp/_MEIuCyOxv/signxml/util/../schemas/xmldsig1-schema.xsd': failed to load external entity "/tmp/_MEIuCyOxv/signxml/util/../schemas/xmldsig1-schema.xsd"
[6343] Failed to execute script script
```

Now with the schemas as a python file

```bash
> git checkout develop
> pyinstaller -F script.py
> ./dist/script
Finished successfully
```

**Comment by kislyuk** [comment]
Thanks. I'm not sure why `--add-data` is not working for you there.

I'm going to reopen this issue and leave it open for visibility. I am not familiar with pyinstaller and its conventions for bundling files (which are apparently incompatible with setuptools). We need a pyinstaller expert to chime in here. I am open to modifying setup.py for this package to get the appropriate configuration in place for pyinstaller to work out of the box, but I need specific guidance with documented and supported features used to achieve this.

**Comment by kislyuk** [comment]
@bvanelli the pathlib change looks innocuous to me, but can you explain to me why it works? What is the effective path used with pathlib, and how is it different from the relative path to `signxml/util/../schemas/xmldsig1-schema.xsd` that apparently doesn't work with pyinstaller? I'm happy to accept your PR since it doesn't add anything custom or increase complexity, just curious what difference it makes.

You're free to make a PR to the pyinstaller hooks repo of course - I have no control over that - but it strikes me as a brittle and unmaintainable system if any package that uses standard setuptools data files functionality has to be added to that repo by name.
