### ISSUE TITLE
Support for multiple signatures

### ISSUE THREAD

**Issue by msetina** [XML-Security/signxml#249]
Current verification takes out just one signature. That means that first signature digest in verification tries to calculate digest including the second signature (or more). That means that the digest of the first signature is wrong.

File "/.local/lib/python3.10/site-packages/signxml/verifier.py", line 481, in _verify_reference
    raise InvalidDigest(f"Digest mismatch for reference {index} ({reference.get('URI')})")
signxml.exceptions.InvalidDigest: Digest mismatch for reference 0 ()

**Comment by kislyuk** [comment]
Can you give a concrete example of an XML document with multiple signatures that shows the issue that you describe?

**Comment by msetina** [comment]
I tried to sign the same document multiple times in a row and verification failed with described problem.

**Comment by kislyuk** [comment]
Hmm, that doesn't sound like a valid use case for this library. Signing the same document multiple times is not something that we support. Perhaps the bug here is that there is no clear error message indicating this condition.

In general, the presence of multiple signatures is a problem, as it creates inherent ambiguities that make it difficult to safely operate regardless of the validity of any of them, so this library will produce an error by default in the presence of such a situation. But if you have a specific, practical use case for signing the document multiple times, please provide a complete, concrete example of what you're trying to do and your counterparty, and we can investigate.

Specifically, you say:

> first signature digest in verification tries to calculate digest including the second signature (or more). That means that the digest of the first signature is wrong.

The standard specifies that in an enveloped signature transform, only the current (under construction) signature node is excised from the data covered by the transform. Any previous signature nodes remain intact.

**Comment by msetina** [comment]
This document covers signing (https://www.w3.org/Signature/Drafts/xmldsig-scenarios-990818.html) and it also covers multiple signers.
As is xmldsig does not limit number of signatures. I understand the part where validation takes out the signature it is validating and this is not part of the problem. As you stated, the prevoius signatures remain intact. Nothing is said about consecutive or later signatures. Those are the problem for the verifier as they were not present at the time of signing with the current signature. This is what triggers the exception as the digest takes the future signatures into acount.

**Comment by kislyuk** [comment]
That document is not normative and does not describe the behavior of the standard, which specifies what I described. The side effect (as far as I know) is that signing the same node with an enveloped signature twice renders the first signature invalid.

The solution is not to do that. Use a reference to specify a node that does not enclose the signature.

**Comment by msetina** [comment]
Thanks. The last senstence is gold. I was sidetracked by the fact that XMLSigner did not raise an exception when signing an element that already contains a Signature element. It could say it would be helpful.
Also I was looking for more complex soution where previous signature would be moved to an Object in Signature.
On the other hand I have to find out why xmlsec1 tool fails signature verification when verifing document produced XMLSigner with a Reference URI set to id of an element.
