### ISSUE TITLE
How to sign xml using SHA1

### ISSUE THREAD

**Issue by blitz-cmd** [XML-Security/signxml#252]
Hi,
I want to sign XML using SHA1 but whenever I use the below code, it gives an error: **"SHA1-based algorithms are not supported in the default configuration because they are not secure"**.
The reason I want to use SHA1 is due to a lack of support for other algorithms by the third-party endpoint.

The code:
```
from lxml import etree
from signxml import XMLSigner, XMLVerifier

signer= XMLSigner(
signature_algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1",
digest_algorithm="http://www.w3.org/2000/09/xmldsig#sha1"
)
signed_root=signer.sign(root, key=key, cert=cert)
```

**Comment by kislyuk** [comment]
Please see the project documentation for details on how to use SHA1.

**Comment by kislyuk** [comment]
Apologies, I see that you are trying to _sign_ with SHA1.

Because SHA1 is not secure for digital signature use, SignXML does not have a built-in way to accept a signing configuration using SHA1, and no documentation is provided for doing so. It's possible to subclass and manually reconfigure XMLSigner to bypass this restriction.
