### ISSUE TITLE
X509SerialNumber too long? not a valid value of the atomic type 'xs:integer'

### ISSUE THREAD

**Issue by tonydemark** [XML-Security/signxml#81]
lxml==3.6.4
signxml==2.2.3

When running XMLVerifier().verify(decoded_assertion, x509_cert=cert).signed_xml to verify a SAML assertion it will fail when the X509SerialNumber is a very long integer.

I'm not sure of the exact length it will fail at (I am guessing it is 2**64 or 9223372036854775807), but we are being presented with an assertion with a 39-character integer and we are getting the following exception:

Traceback (most recent call last):
  File "views.py", line 381, in sso
    XMLVerifier().verify(decoded_assertion, x509_cert=cert).signed_xml
  File ".../site-packages/signxml/__init__.py", line 695, in verify
    self.schema().assertValid(signature)
  File "src/lxml/lxml.etree.pyx", line 3491, in lxml.etree._Validator.assertValid (src/lxml/lxml.etree.c:182278)
DocumentInvalid: Element '{http://www.w3.org/2000/09/xmldsig#}X509SerialNumber': '9#####################################0' is not a valid value of the atomic type 'xs:integer'., line 14

**Comment by kislyuk** [comment]
This is a schema validation issue. You can see the schema that signxml uses to verify the SAML assertion contents here: https://github.com/XML-Security/signxml/blob/master/signxml/schemas/xmldsig-core-schema.xsd#L200. The error you see appears to be a bug in the schema or due to an out of date schema that does not admit this large X509SerialNumber. This schema is part of the standard and is outside signxml's control. The validator is part of lxml, also outside our control.

However, there is a workaround - just pass `validate(validate_schema=False)`.

**Comment by tonydemark** [comment]
Thanks!
