### ISSUE TITLE
Insert X509Certificate for signing SAML assertions

### ISSUE THREAD

**Issue by dmwesterhoff** [XML-Security/signxml#88]
Hi, how can I insert into the <ds:KeyInfo> a <ds:X509Certificate> ?

I saw there is a key_info parameter however I cannot create the element to shove in because it is not aware of the ds namespace that is declared by signxml in the <ds:Signature> node.

---

I noticed there is some documentation marked TODO on signing saml assertions so I'm wondering if I'm missing a key piece of information to do this correctly.

**Comment by kislyuk** [comment]
The X509Certificate XML element is automatically generated for you based on the certificate you pass to `sign()`. Also, you can use any namespace that you want for the KeyInfo element passed via `key_info`, including ds (its full form is "http://www.w3.org/2000/09/xmldsig#").

I'm not sure what you mean by "it is not aware", can you elaborate?

Are you having a specific problem with how the signature looks vs. how you need it to look? If so, please provide a concrete example.

The docs have that TODO tag because I haven't come up with a good illustrative example yet. This library certainly does get used in multiple implementations of SAML assertion signing though.

**Comment by dmwesterhoff** [comment]
Ok I have progressed and can be much more coherent now that I've been looking at this a little longer. What I am attempting to do it sign a SAML assertion using enveloped signing.

Here's what I tried:
Inserting placeholder between Issuer and subject in the assertion:
...
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="placeholder></ds:Signature>

When using methods.enveloped this inserts the ds:Signature element properly except for the fact that the X509 Certificate is inserted with line breaks.

What I have found out though that is interesting is that when I omit the Signature placeholder line from my assertion it attaches the Signature automatically at the bottom of the assertion element. And this time the X509 is properly formatted with no line breaks! 
---
Im sure that I'm missing something here. But I feel like I'm very close. Any thoughts? Can you point me to any example of signing a SAML assertion with signxml?

**Comment by dmwesterhoff** [comment]
Even though I'm sure I must be misusing the library based off what you said I was able to get the cert to format without the line breaks by modifying this line in `sign` to
`x509_certificate.text = strip_pem_header(cert).replace('\n', '')`

**Comment by kislyuk** [comment]
OK, this gives better information about what you're trying to do, but it's not complete yet. Why do you require that the base64 encoded certificate text contain no linebreaks? Does your SAML peer reject the assertion when it contains line breaks?

I agree that there should be a SAML assertion signing example in the docs, I will try to get that done soon.

**Comment by kislyuk** [comment]
Closing due to lack fo response.
